# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-27 18:33
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreedAM_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='framedimensions',
            old_name='backrest_height',
            new_name='shoulder_height',
        ),
        migrations.AlterField(
            model_name='contact',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 18, 33, 18, 377000)),
        ),
        migrations.AlterField(
            model_name='framedimensions',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 18, 33, 18, 642000)),
        ),
        migrations.AlterField(
            model_name='framedimensions',
            name='seat_depth',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Buttock to knee length'),
        ),
        migrations.AlterField(
            model_name='framedimensions',
            name='seat_width',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Hip breadth'),
        ),
    ]
