# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-27 19:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreedAM_app', '0002_auto_20190227_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 19, 19, 14, 765000)),
        ),
        migrations.AlterField(
            model_name='framedimensions',
            name='angle_lower_leg_upper_leg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='framedimensions',
            name='backrest_angle',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='framedimensions',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 19, 19, 14, 790000)),
        ),
        migrations.AlterField(
            model_name='framedimensions',
            name='seat_depth',
            field=models.IntegerField(verbose_name='Buttock to knee length'),
        ),
        migrations.AlterField(
            model_name='framedimensions',
            name='seat_height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='framedimensions',
            name='seat_width',
            field=models.IntegerField(verbose_name='Hip breadth'),
        ),
        migrations.AlterField(
            model_name='framedimensions',
            name='seating_angle',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='framedimensions',
            name='shoulder_height',
            field=models.IntegerField(),
        ),
    ]
