# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-16 11:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreedAM_app', '0005_auto_20190309_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='cushion_type',
            field=models.CharField(choices=[('Comfort Basic', 'Comfort Basic'), ('Comfort Gel', 'Comfort Gel'), ('Comfort Foam', 'Comfort Foam'), ('Memory Foam', 'Memory Foam'), ('Luxury Fleece', 'Luxury Fleece')], default='1', max_length=16),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 11, 43, 18, 989000)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 11, 43, 18, 973000)),
        ),
        migrations.AlterField(
            model_name='framedimensions',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 11, 43, 18, 989000)),
        ),
    ]
