# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-16 12:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreedAM_app', '0006_auto_20190316_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='storage',
            field=models.CharField(choices=[('Utility bag', 'Utility bag'), ('Horizontal utility bag', 'Horizontal utility bag'), ('Side pouch', 'Side pouch')], default='1', max_length=16),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 12, 27, 51, 873000)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 12, 27, 51, 839000)),
        ),
        migrations.AlterField(
            model_name='framedimensions',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 16, 12, 27, 51, 872000)),
        ),
    ]
