# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-22 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreedAM_app', '0007_auto_20190316_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='framedimensions',
            name='your_name',
            field=models.CharField(default='Your nickname', max_length=250),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 17, 5, 45, 558000)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 17, 5, 45, 523000)),
        ),
        migrations.AlterField(
            model_name='framedimensions',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 22, 17, 5, 45, 556000)),
        ),
    ]
